proxies:
proxy-providers:
 Akun-VPN:
    type: file
    path: "./vpn.yaml"
    url: https://raw.githubusercontent.com/wwahyudm/2024/refs/heads/main/vpn.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: VPN
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - Akun-VPN
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: Game
  type: select
  proxies:
  - DIRECT
  - VPN
- name: AdBlock
  type: select
  proxies:
  - VPN
  - REJECT
- name: Safe Child
  type: select
  proxies:
  - VPN
  - REJECT
rule-providers:
  Rule_Whatsapp:
    type: file
    behavior: classical
    path: "./rule_whatsapp.yaml"
  Rule_AdBlock:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_basicads.yaml
    path: "./rule_basicads.yaml"
    interval: 86400
  Rule_Gaming:
    type: http
    behavior: classical
    path: "./rule_gaming.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_gaming.yaml
    interval: 86400
  Rule_Portgames:
    type: http
    behavior: classical
    path: "./rule_portgames.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_portgames.yaml
    interval: 86400
  Rule_Personalads:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_personalads.yaml
    path: "./rule_personalads.yaml"
    interval: 86400
  Rule_Porn:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_porn.yaml
    path: "./rule_porn.yaml"
    interval: 86400
  Rule_Nsfw:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_nsfw.yaml
    path: "./rule_nsfw.yaml"
    interval: 86400
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,Rule_AdBlock,AdBlock
- RULE-SET,Rule_Personalads,AdBlock
- RULE-SET,Rule_Porn,Safe Child
- RULE-SET,Rule_Nsfw,Safe Child
- RULE-SET,Rule_Portgames,Game
- RULE-SET,Rule_Gaming,Game
- RULE-SET,Rule_Whatsapp,DIRECT
- GEOSITE,LINE,DIRECT
- GEOSITE,YOUTUBE,DIRECT
- GEOSITE,FACEBOOK,DIRECT
- GEOSITE,INSTAGRAM,DIRECT
- MATCH,VPN
